name: masterji_user_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  cached_network_image: ^2.2.0+1
  razorpay_flutter: 1.1.3
  intl: ^0.16.0
  google_maps_flutter: ^0.5.28+1
  flutter_map_picker: ^0.1.2
  firebase_auth: ^0.15.3+1
  cloud_firestore: ^0.13.6
  dotted_border: ^1.0.5
  flutter_svg: ^0.17.4
  dots_indicator: ^1.0.0
  firebase_messaging: ^6.0.16
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider_architecture: ^1.0.3
  responsive_builder: ^0.1.4
  provider: ^3.2.0
  logger: ^0.7.0+2
  get_it: ^3.0.3
  flutter_localizations:
    sdk: flutter
  flutter_html: ^1.0.0  
  equatable: ^1.0.1
  shared_preferences: ^0.5.6+3
  url_launcher: ^5.4.5
  geolocator: ^5.3.1
  flushbar: ^1.10.2
  flutter_screenutil: ^1.1.0
  dio:
  firebase_analytics: ^5.0.11
  flutter_phoenix: "^0.1.0"
  flutter_page_transition: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assests/images/applogo.png"

flutter:
  uses-material-design: true
  assets:
    - locale/i18n_en.json
    - locale/i18n_hi.json
    - assests/images/
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assests/fonts/MyFlutterApp.ttf
    - family: Stitch
      fonts:
        - asset: assests/fonts/Stitch.ttf
    - family: Helvatica
      fonts:
        - asset: assests/fonts/helvetica.ttf
    - family: MobiApp
      fonts:
        - asset: assests/fonts/MobiApp.ttf
    - family: OTPApp
      fonts:
        - asset: assests/fonts/OTPApp.ttf    
          
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
