/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData profile =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orders =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fabric =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faq =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fashion =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const familiy = 'Stitch';

  static const IconData stitch =
      IconData(0xe801, fontFamily: familiy, fontPackage: _kFontPkg);

  static const family = 'Logo';
  static const IconData masterji_logo =
      IconData(0xe800, fontFamily: family, fontPackage: _kFontPkg);

static const fontfamiliy = 'MobiApp';


  static const IconData mobi = IconData(0xe800, fontFamily: fontfamiliy, fontPackage: _kFontPkg);
  static const fontOTP= 'OTPApp';
 
  static const IconData otp = IconData(0xe800, fontFamily: fontOTP, fontPackage: _kFontPkg);
}
